### ISSUE TITLE
Module 1 - 5. Evaluate the model

### ISSUE THREAD

**Issue by gdequeiroz** [CODAIT/max-developer-tutorial#3]
In this [item](https://github.com/CODAIT/max-developer-tutorial/tree/master/modules/module1#running-the-pre-built-docker-image
), 
![image](https://user-images.githubusercontent.com/1934546/48740360-fdb39400-ec0b-11e8-9cf6-b40c01d3968a.png)
 I'm not sure we should call this 'Evaluate the model'. From my understanding, when you are evaluating the model, you want to determine if the model will do a good job of predicting the target on new and future data. In this case we are predicting or inferencing.

(cc @MLnick)

**Comment by ptitzler** [comment]
I see the ambiguity. I used the term to convey that the reader should try out the prediction endpoint. Maybe change it to "Try out the prediction endpoint" to be clearer?

**Comment by gdequeiroz** [comment]
It sounds better to me.

**Comment by MLnick** [comment]
@ptitzler Agree with your proposed alternative
